/*Copyright 2010 George Karagoulis

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.*/

#include "gdatabaseiodevice.h"
#include "DataObjects/DataSet/datatable.h"
#include "DataObjects/DataSet/datarow.h"
#include <QSqlQuery>
#include <QSqlError>
#include <QSqlResult>
using namespace GUtil;
using namespace DataObjects;
using namespace DataAccess;

GDatabaseIODevice::GDatabaseIODevice(const QString &db_connection_id,
                                     QObject *parent)
    :GIODevice(parent),
    _p_WriteCommand(Noop),
    _selection_parameters(new DataTable()),
    _connection(db_connection_id)
{}

GDatabaseIODevice::~GDatabaseIODevice()
{
    delete _selection_parameters;
    QSqlDatabase::database(_connection).close();
    QSqlDatabase::removeDatabase(_connection);
}

void GDatabaseIODevice::send_data(const QByteArray &d)
        throw(Core::DataTransportException)
{
    DataTable t;
    try
    {
        t.FromXmlQString(d);
    }
    catch(Core::XmlException &ex)
    {
        THROW_NEW_GUTIL_EXCEPTION3(Core::DataTransportException,
                                  "Not a valid XML string",
                                  ex);
    }

    if(t.ColumnCount() == 0 || t.RowCount() == 0)
        THROW_NEW_GUTIL_EXCEPTION2(Core::DataTransportException,
                                   "No data to send");

    QSqlDatabase _database = QSqlDatabase::database(_connection);
    if(!_database.isOpen() && !_database.open())
        THROW_NEW_GUTIL_EXCEPTION2(Core::DataTransportException,
                                   QString("Unable to open database: %1")
                                   .arg(_database.lastError().text()).toStdString());

    try
    {
        for(int i = 0; i < t.RowCount(); i++)
        {
            DataRow row(t[i]);

            QSqlQuery query(_database);
            QString where;
            QString values;
            switch(GetWriteCommand())
            {
            case Insert:
                for(int j = 0; j < t.ColumnCount(); j++)
                {
                    values.append("?,");
                    where.append(QString("%1,").arg(t.ColumnKeys()[j]));
                }

                // Remove the trailing comma
                values.remove(values.length() - 1, 1);
                where.remove(where.length() - 1, 1);

                // Prepare the query string
                query.prepare(QString("INSERT INTO %1 (%2) VALUES (%3)")
                      .arg(t.Name())
                      .arg(where)
                      .arg(values));

                // Bind values after preparing the query
                for(int j = 0; j < t.ColumnCount(); j++)
                    query.addBindValue(row[j]);

                break;
            case Update:
                if(t.KeyColumns().count() == 0)
                    THROW_NEW_GUTIL_EXCEPTION2(Core::DataTransportException,
                                               "The table is required to have"
                                               " at least one key column");

                for(int j = 0; j < t.KeyColumns().count(); j++)
                {
                    // The where clause is generated by looking at the key
                    //  columns which have non-null values, and the
                    //  values clause is made by looking at all other columns
                    //  with a value.
                }

                break;
            case Delete:
                for(int j = 0; j < t.ColumnCount(); j++)
                {
                    if(!row[j].isNull())
                    {
                        where.append(QString("%1=? AND ")
                                    .arg(t.ColumnKeys()[j]));
                    }
                }

                if(where.length() == 0)
                    THROW_NEW_GUTIL_EXCEPTION2(Core::DataTransportException,
                                               "No parameters set for deletion");

                // Remove the trailing 'and'
                where.remove(where.length() - 5, 5);

                query.prepare(QString("DELETE FROM %1 WHERE %2")
                      .arg(t.Name())
                      .arg(where));

                for(int j = 0; j < t.ColumnCount(); j++)
                {
                    if(!row[j].isNull())
                        query.addBindValue(row[j]);
                }

                break;
            default:
                return;
            }

            if(query.exec())
            {
                _p_ReturnValue.clear();

                switch(GetWriteCommand())
                {
                case Insert:
                    break;
                case Update:
                    break;
                case Delete:
                    // This is supposed to return the number of rows affected,
                    //  but I'm not sure if that's what it does
                    _p_ReturnValue = query.value(0);
                    break;
                default:
                    return;
                }
            }
            else
            {
                Core::DataTransportException ex("Query Failed");
                ex.SetData("db_name", _database.databaseName().toStdString());
                ex.SetData("error", query.lastError().text().toStdString());
                ex.SetData("query", query.lastQuery().toStdString());
                ex.SetData("executed", query.executedQuery().toStdString());

                for(int k = 0; k < query.boundValues().count(); k++)
                {
                    ex.SetData(QString("Bound Value %1").arg(k).toStdString(),
                               query.boundValue(k).toString().toStdString());
                }

                THROW_GUTIL_EXCEPTION(ex);
            }
        }
    }
    catch(Core::Exception &)
    {
        throw;
    }
}

QByteArray GDatabaseIODevice::receive_data()
        throw(Core::DataTransportException)
{
    if(_selection_parameters->RowCount() == 0 ||
       _selection_parameters->ColumnCount() == 0)
        THROW_NEW_GUTIL_EXCEPTION2( Core::DataTransportException,
                                    "You have not specified any parameters "
                                    "for the selection");

    QByteArray ret;
    QString values, where;
    QSqlDatabase _database = QSqlDatabase::database(_connection);

    if(!_database.isOpen() && !_database.open())
        THROW_NEW_GUTIL_EXCEPTION2(Core::DataTransportException,
                                   QString("Unable to open database: %1")
                                   .arg(_database.lastError().text()).toStdString());

    QSqlQuery query(_database);

    try
    {
        DataRow r(_selection_parameters->Rows()[0]);

        for(int i = 0; i < _selection_parameters->ColumnCount(); i++)
        {
            values.append(QString("%1,")
                          .arg(_selection_parameters->ColumnKeys()[i]));

            if(!r[i].isNull())
            {
                where.append(QString("%1=? AND ")
                          .arg(_selection_parameters->ColumnKeys()[i]));
            }
        }

        values.remove(values.length() - 1, 1);
        if(where.length() > 0)
        {
            where.remove(where.length() - 5, 5);

            where = QString("WHERE %1").arg(where);
        }


        QString sql(QString("SELECT %1 FROM %2")
                    .arg(values)
                    .arg(_selection_parameters->Name()));

        if(where.length() > 0)
            sql = QString("%1 %2").arg(sql).arg(where);

        query.prepare(sql);

        // Bind values after preparing the query
        for(int i = 0; i < _selection_parameters->ColumnCount(); i++)
        {
            if(!r[i].isNull())
                query.addBindValue(r[i], QSql::InOut);
        }

        if(query.exec())
        {
            DataTable tbl(_selection_parameters->Name());
            tbl.SetColumnHeaders(_selection_parameters->ColumnKeys(),
                                 _selection_parameters->ColumnLabels());
            while(query.next())
            {
                Custom::GVariantList lst;
                for(int i = 0; i < _selection_parameters->ColumnCount(); i++)
                    lst.append(query.value(i));
                tbl.AddNewRow(lst);
            }

            ret = tbl.ToXmlQString().toAscii();

            // Remove the row now that we've processed the query
            tbl.RemoveRow(0);
        }
        else
        {
            Core::DataTransportException ex("Query Failed");
            ex.SetData("db_name", _database.databaseName().toStdString());
            ex.SetData("error", query.lastError().text().toStdString());
            ex.SetData("query", query.lastQuery().toStdString());
            ex.SetData("executed", query.executedQuery().toStdString());

            for(int k = 0; k < query.boundValues().count(); k++)
            {
                ex.SetData(QString("Bound Value %1").arg(k).toStdString(),
                           query.boundValue(k).toString().toStdString());
            }

            THROW_GUTIL_EXCEPTION(ex);
        }
    }
    catch(Core::Exception &)
    {
        throw;
    }

    return ret;
}

bool GDatabaseIODevice::has_data_available()
{
    // We can always query the database for more data
    return true;
}
